// AUTO-GENERATED MAP FOR LOCAL ASSETS
export const IMAGES_MAP = {
  "dall_e_2025_02_13_13_29_49___a_cartoon_style_drawing_of_a_long__stylish_necktie_with_a_modern_design__the_tie_features_bold_diagonal_stripes_in_vibrant_colors__such_as_red_and_bla": require("../../assets/Images du thème 3/DALL·E 2025-02-13 13.29.49 - A cartoon-style drawing of a long, stylish necktie with a modern design. The tie features bold diagonal stripes in vibrant colors, such as red and bla.webp"),
  "dall_e_2025_02_13_13_30_57___a_cartoon_style_drawing_of_a_stylish_jacket_with_a_modern_design__the_jacket_has_a_sleek_fit__elegant_lapels__and_bold__exaggerated_lines_for_a_fun_an": require("../../assets/Images du thème 3/DALL·E 2025-02-13 13.30.57 - A cartoon-style drawing of a stylish jacket with a modern design. The jacket has a sleek fit, elegant lapels, and bold, exaggerated lines for a fun an.webp"),
  "dall_e_2025_02_13_13_36_50___a_cartoon_style_drawing_of_a_pair_of_african_traditional_shoes_with_bold_outlines_and_vibrant_colors__the_shoes_feature_intricate_patterns_inspired_by": require("../../assets/Images du thème 3/DALL·E 2025-02-13 13.36.50 - A cartoon-style drawing of a pair of African traditional shoes with bold outlines and vibrant colors. The shoes feature intricate patterns inspired by.webp"),
  "dall_e_2025_02_13_13_48_37___a_cartoon_style_drawing_of_a_simple_pair_of_traditional_babouches__the_shoes_have_a_minimalistic_design_with_smooth_curves__warm_earthy_colors_like_be": require("../../assets/Images du thème 3/DALL·E 2025-02-13 13.48.37 - A cartoon-style drawing of a simple pair of traditional babouches. The shoes have a minimalistic design with smooth curves, warm earthy colors like be.webp"),
  "leonardo_phoenix_10_a_single_isolated_and_whimsically_stylized_0": require("../../assets/Images du thème 3/Leonardo_Phoenix_10_a_single_isolated_and_whimsically_stylized_0.jpg"),
  "leonardo_phoenix_10_a_white_casual_crewneck_tshirt_with_a_cart_0": require("../../assets/Images du thème 3/Leonardo_Phoenix_10_a_white_casual_crewneck_tshirt_with_a_cart_0.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_confiden_3": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_confiden_3.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_group_of_3": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_group_of_3.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_joyful_a_1": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_joyful_A_1.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_loving_a_3": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_loving_A_3.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_loving_e_1": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_loving_e_1.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_proud_af_2": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_proud_Af_2.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_warm_and_3": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_warm_and_3.jpg"),
  "dall_e_2025_02_12_08_54_35___a_realistic_cartoon_style_cockroach_with_natural_features__the_cockroach_has_a_shiny_brown_exoskeleton__long_segmented_antennae__and_six_legs_with_sma": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/DALL·E 2025-02-12 08.54.35 - A realistic cartoon-style cockroach with natural features. The cockroach has a shiny brown exoskeleton, long segmented antennae, and six legs with sma.webp"),
  "leonardo_phoenix_10_a_vibrant_colorful_cartoon_illustration_of_0": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_A_vibrant_colorful_cartoon_illustration_of_0.jpg"),
  "leonardo_phoenix_10_a_whimsical_and_vibrant_animated_scene_dep_0": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_A_whimsical_and_vibrant_animated_scene_dep_0.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_group_of_0": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_group_of_0.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_majestic_0": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_majestic_0.jpg"),
  "leonardo_phoenix_10_a_serene_and_lifelike_cartoon_elephant_sta_0": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_a_serene_and_lifelike_cartoon_elephant_sta_0.jpg"),
  "leonardo_phoenix_10_a_solitary_majestic_sparrowhawk_in_full_fl_0": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_a_solitary_majestic_sparrowhawk_in_full_fl_0.jpg"),
  "leonardo_phoenix_10_a_beautifully_lit_ornate_glass_bottle_fill_0": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_beautifully_lit_ornate_glass_bottle_fill_0.jpg"),
  "leonardo_phoenix_10_a_cartoon_depiction_of_a_traditional_afric_0": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_cartoon_depiction_of_a_traditional_Afric_0.jpg"),
  "leonardo_phoenix_10_a_delicate_powdery_cloud_of_white_flour_sp_0__1_": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_delicate_powdery_cloud_of_white_flour_sp_0 (1).jpg"),
  "leonardo_phoenix_10_a_vibrant_dynamic_image_of_fire_depicting_0": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_vibrant_dynamic_image_of_Fire_depicting_0.jpg"),
  "leonardo_phoenix_10_highly_detailed_realistic_and_vibrant_cart_0": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_Highly_detailed_realistic_and_vibrant_cart_0.jpg"),
  "leonardo_phoenix_10_a_vibrant_playful_cartoon_illustration_of_0": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_a_vibrant_playful_cartoon_illustration_of_0.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_confiden_3": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_confiden_3.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_group_of_3": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_group_of_3.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_joyful_a_1": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_joyful_A_1.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_loving_a_3": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_loving_A_3.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_loving_e_1": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_loving_e_1.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_proud_af_2": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_proud_Af_2.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_warm_and_3": require("../../assets/Les images de muléma/Images du theme 0 des exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_warm_and_3.jpg"),
  "dall_e_2025_02_12_08_54_35___a_realistic_cartoon_style_cockroach_with_natural_features__the_cockroach_has_a_shiny_brown_exoskeleton__long_segmented_antennae__and_six_legs_with_sma": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/DALL·E 2025-02-12 08.54.35 - A realistic cartoon-style cockroach with natural features. The cockroach has a shiny brown exoskeleton, long segmented antennae, and six legs with sma.webp"),
  "leonardo_phoenix_10_a_vibrant_colorful_cartoon_illustration_of_0": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_A_vibrant_colorful_cartoon_illustration_of_0.jpg"),
  "leonardo_phoenix_10_a_whimsical_and_vibrant_animated_scene_dep_0": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_A_whimsical_and_vibrant_animated_scene_dep_0.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_group_of_0": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_group_of_0.jpg"),
  "leonardo_phoenix_10_vibrant_cartoon_illustration_of_a_majestic_0": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_Vibrant_cartoon_illustration_of_a_majestic_0.jpg"),
  "leonardo_phoenix_10_a_serene_and_lifelike_cartoon_elephant_sta_0": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_a_serene_and_lifelike_cartoon_elephant_sta_0.jpg"),
  "leonardo_phoenix_10_a_solitary_majestic_sparrowhawk_in_full_fl_0": require("../../assets/Les images de muléma/Images du theme 1 de tout les exercises/Leonardo_Phoenix_10_a_solitary_majestic_sparrowhawk_in_full_fl_0.jpg"),
  "leonardo_phoenix_10_a_beautifully_lit_ornate_glass_bottle_fill_0": require("../../assets/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_beautifully_lit_ornate_glass_bottle_fill_0.jpg"),
  "leonardo_phoenix_10_a_cartoon_depiction_of_a_traditional_afric_0": require("../../assets/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_cartoon_depiction_of_a_traditional_Afric_0.jpg"),
  "leonardo_phoenix_10_a_delicate_powdery_cloud_of_white_flour_sp_0__1_": require("../../assets/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_delicate_powdery_cloud_of_white_flour_sp_0 (1).jpg"),
  "leonardo_phoenix_10_a_vibrant_dynamic_image_of_fire_depicting_0": require("../../assets/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_A_vibrant_dynamic_image_of_Fire_depicting_0.jpg"),
  "leonardo_phoenix_10_highly_detailed_realistic_and_vibrant_cart_0": require("../../assets/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_Highly_detailed_realistic_and_vibrant_cart_0.jpg"),
  "leonardo_phoenix_10_a_vibrant_playful_cartoon_illustration_of_0": require("../../assets/Les images de muléma/Images du thème 2/Leonardo_Phoenix_10_a_vibrant_playful_cartoon_illustration_of_0.jpg"),
  "android_icon_background": require("../../assets/images/android-icon-background.png"),
  "android_icon_foreground": require("../../assets/images/android-icon-foreground.png"),
  "android_icon_monochrome": require("../../assets/images/android-icon-monochrome.png"),
  "avatar_cuisine": require("../../assets/images/avatar-cuisine.webp"),
  "avatar_famille": require("../../assets/images/avatar-famille.png"),
  "avatar_felix": require("../../assets/images/avatar-felix.png"),
  "avatar_kandem": require("../../assets/images/avatar-kandem.avif"),
  "avatar_kandem": require("../../assets/images/avatar-kandem.png"),
  "avatar_ngon": require("../../assets/images/avatar-ngon.avif"),
  "avatar_ngon": require("../../assets/images/avatar-ngon.png"),
  "avatar_paul": require("../../assets/images/avatar-paul.png"),
  "avatar_sophie": require("../../assets/images/avatar-sophie.avif"),
  "avatar_sophie": require("../../assets/images/avatar-sophie.png"),
  "avatar_tjega": require("../../assets/images/avatar-tjega.avif"),
  "avatar_tjega": require("../../assets/images/avatar-tjega.png"),
  "avatar_user": require("../../assets/images/avatar-user.png"),
  "avatar_vetement": require("../../assets/images/avatar-vetement.png"),
  "boat": require("../../assets/images/boat.png"),
  "camel": require("../../assets/images/camel.png"),
  "colla": require("../../assets/images/colla.png"),
  "favicon": require("../../assets/images/favicon.png"),
  "forgot": require("../../assets/images/forgot.png"),
  "icon": require("../../assets/images/icon.png"),
  "island": require("../../assets/images/island.png"),
  "jungle_background": require("../../assets/images/jungle_background.jpg"),
  "lock": require("../../assets/images/lock.png"),
  "logo": require("../../assets/images/logo.png"),
  "mountain_large": require("../../assets/images/mountain-large.png"),
  "mountain_small": require("../../assets/images/mountain-small.png"),
  "otp": require("../../assets/images/otp.png"),
  "pyramid_small": require("../../assets/images/pyramid-small.png"),
  "reset": require("../../assets/images/reset.webp"),
  "sign_in": require("../../assets/images/sign-in.png"),
  "sign_up": require("../../assets/images/sign-up.png"),
  "sphinx": require("../../assets/images/sphinx.png"),
  "splash_icon": require("../../assets/images/splash-icon.png"),
  "winding_path": require("../../assets/images/winding_path.jpg"),
};

export const AUDIOS_MAP = {
  "mama_en_langue_nghomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/Mama en langue nghomala.wav"),
  "la_tante_maternelleen_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/la tante maternelleen ngohmala.wav"),
  "la_tante_paternelle_en_nghomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/la tante paternelle en nghomala.wav"),
  "le_bebe_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/le bebe en ngohmala.wav"),
  "les_amis_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/les amis en ngohmala.wav"),
  "les_enfants_en_nghomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/les enfants en nghomala.wav"),
  "les_grand_parents_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/les grand parents en ngohmala.wav"),
  "loncle_maternel_en_nghomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/loncle maternel en nghomala.wav"),
  "loncle_paternel_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/loncle paternel en ngomala.wav"),
  "papa_en_langue_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/papa en langue ngomala.wav"),
  "exer_n2_rpsne_1_papa_": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/Exer N2 Rpsne 1(papa).wav"),
  "exer_n2_rpsne_2": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/exer N2 Rpsne 2.wav"),
  "exer_n2_rpsne_3__les_enfants_": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/exer N2 Rpsne 3 (les enfants).wav"),
  "exer_n2_rpsne_4": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/exer N2 Rpsne 4.wav"),
  "exer_n3_rpsne_5": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/Exer N3 Rpsne 5.wav"),
  "exer_n6_rpsne_2": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer N6 Rpsne 2.wav"),
  "exer_n6_rpsne_3": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer N6 Rpsne 3.wav"),
  "exer_n6_rpsne_4": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer N6 Rpsne 4.wav"),
  "exer_n6_rpsne_1": require("../../assets/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer n6 Rpsne 1.wav"),
  "l_huile_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/L'huile en ngomala.wav"),
  "le_poulet_en_ngomala__ca_ne_change_pasau_pluriel_": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/Le poulet en ngomala (ca ne change pasau pluriel).wav"),
  "le_boeuf_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/le boeuf en ngomala.wav"),
  "le_lion_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/le lion en ngomala.wav"),
  "le_poisson_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/le poisson en ngohmala.wav"),
  "les_termites_en_langue_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/les Termites en langue ngomala.wav"),
  "exer_2_rpsne_1": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 1.wav"),
  "exer_2_rpsne_2": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 2.wav"),
  "exer_2_rpsne_3__les_sangliers_": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 3 [les sangliers].wav"),
  "exer_2_rpsne_4": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 4.wav"),
  "exer_2_rpsne_n5__l_elephant_": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne N5 [l'elephant].wav"),
  "exer_3_rpsne_1__l_abeille_": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 Rpsne 1[ l'abeille].wav"),
  "exer_3_rpsne_3": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 Rpsne 3.wav"),
  "exer_3_rpsne_n4___les_singes_": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 Rpsne N4 [ les singes].wav"),
  "exer_3_rpsne_2__la_sauterelle_": require("../../assets/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 rpsne 2 [la sauterelle].wav"),
  "l_huile_en_ngohmala___theme_2_exer_1_": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/L'huile en ngohmala [ theme 2 exer 1].wav"),
  "la_farine_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/La farine en ngohmala.wav"),
  "la_flamme_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/La flamme en ngohmala.wav"),
  "la_piere_a_ecrasser_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/La piere a ecrasser en ngohmala.wav"),
  "le_sucre_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le Sucre en ngohmala.wav"),
  "le_couteau_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le couteau en ngohmala.wav"),
  "le_mortier_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le mortier en ngohmala.wav"),
  "le_sel_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le sel en ngohmala.wav"),
  "l_eau_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/l'eau en ngohmala.wav"),
  "le_feu_en_ngohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/le feu en ngohmala.wav"),
  "exer_2_rpsne_1": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 1.wav"),
  "exer_2_rpsne_2": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 2.wav"),
  "exer_2_rpsne_3": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 3.wav"),
  "exer_2_rpsne_4": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 4.wav"),
  "exer_2_rpsne_5": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 5.wav"),
  "exer_2_rpsne_n2": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 2 Rpsne N2.wav"),
  "exer_3_rpsne_n1": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 Rpsne N1.wav"),
  "exer_3_rpsne_n4": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 Rpsne N4.wav"),
  "exer_3_rpsne_n5": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 Rpsne N5.wav"),
  "exer_3_rpsne_n3": require("../../assets/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 rpsne N3.wav"),
  "ce_chapau": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ce chapau.wav"),
  "ce_mentau": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ce mentau.wav"),
  "ces_boubous": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ces boubous.wav"),
  "ces_calecon_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ces calecon en ngomala.wav"),
  "ces_costumes_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ces costumes en ngomala.wav"),
  "cette_chaussure_en_ngomala": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette chaussure en ngomala.wav"),
  "cette_chemise_en_gohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette chemise en gohmala.wav"),
  "cette_cullote": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette cullote.wav"),
  "cette_habit_en_gohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette habit en gohmala.wav"),
  "ce_pentalon": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/ce pentalon.wav"),
  "cette_chemise_gohmala": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/cette chemise gohmala.wav"),
  "exer_2_rpsne_1__la_cravate_": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 2 Rpsne 1 [la cravate].wav"),
  "exer_2_rpsne_2": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 2 Rpsne 2.wav"),
  "exer_2_rpsne_3": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 2 Rpsne 3.wav"),
  "exer_3_rpsne_4": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 3 Rpsne 4.wav"),
  "exer_3_rpsne_4__les_pairs_de_babouche_": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne 4 (les pairs de babouche).wav"),
  "exer_3_rpsne_n1__la_vesste_": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne N1 [la vesste].wav"),
  "exer_3_rpsne_n2": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne N2.wav"),
  "exer_3_rpsne_n3": require("../../assets/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne N3.wav"),
  "dimanche": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/dimanche.wav"),
  "jeudi": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/jeudi.wav"),
  "lundi": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/lundi.wav"),
  "mardi": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/mardi.wav"),
  "mercredi": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/mercredi.wav"),
  "samedi": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/samedi.wav"),
  "vendredi": require("../../assets/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/vendredi.wav"),
  "il_ou_elle_a": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/il ou elle a.wav"),
  "ils_ou_elles_ont": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/ils ou elles ont.wav"),
  "j_aiwav": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/j'aiwav.wav"),
  "nous_avons": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/nous avons.wav"),
  "tu_as": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/tu as.wav"),
  "vous_avez": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/vous avez.wav"),
  "il_ou_elle_mange": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/il ou elle mange.wav"),
  "ils_ou_elle_mangent": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/ils ou elle mangent.wav"),
  "je_mange": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/je mange.wav"),
  "nous_mangeons": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/nous mangeons.wav"),
  "tu_manges": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/tu manges.wav"),
  "vous_mangez": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/vous mangez.wav"),
  "il_ou_elle_marche": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/il ou elle marche.wav"),
  "ils_ou_elles_marchent": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/ils ou elles marchent.wav"),
  "je_marche": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/je marche.wav"),
  "nous_marchons": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/nous marchons.wav"),
  "tu_marches": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/tu marches.wav"),
  "vous_marchez": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/vous marchez.wav"),
  "il_ou_elle_achete": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/il ou elle achete.wav"),
  "ils_ou_elles_achetent": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/ils ou elles achetent.wav"),
  "j_achete": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/j'achete.wav"),
  "nous_achetons": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/nous achetons.wav"),
  "tu_achetes": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/tu achetes.wav"),
  "vous_achetez": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/vous achetez.wav"),
  "il_elle_on_est__1_": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/il elle on est (1).wav"),
  "ils_elles_sont__1_": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/ils elles sont (1).wav"),
  "je_suis__1_": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/je suis (1).wav"),
  "nous_sommes__1_": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/nous sommes (1).wav"),
  "tu_es__2_": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/tu es (2).wav"),
  "vous_etes__1_": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/vous etes (1).wav"),
  "il_ou_elle_prend": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/il ou elle prend.wav"),
  "ils_ou_elles_prennent": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/ils ou elles prennent.wav"),
  "je_prends": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/je prends.wav"),
  "nous_prenons": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/nous prenons.wav"),
  "tu_prends": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/tu prends.wav"),
  "vous_prenez": require("../../assets/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/vous prenez.wav"),
  "il_elle__on_a": require("../../assets/Les lecons douala/Le verbe avoir/il elle  on a.wav"),
  "ils_elles_ont": require("../../assets/Les lecons douala/Le verbe avoir/ils elles ont.wav"),
  "j_ai": require("../../assets/Les lecons douala/Le verbe avoir/j ai.wav"),
  "nous_avons": require("../../assets/Les lecons douala/Le verbe avoir/nous avons.wav"),
  "tu_as": require("../../assets/Les lecons douala/Le verbe avoir/tu as.wav"),
  "vous_avez": require("../../assets/Les lecons douala/Le verbe avoir/vous avez.wav"),
  "il_elle_est": require("../../assets/Les lecons douala/Le verbe etre/IL ELLE EST.wav"),
  "ils_elles_sont": require("../../assets/Les lecons douala/Le verbe etre/ILS ELLES SONT.wav"),
  "nous_sommes": require("../../assets/Les lecons douala/Le verbe etre/NOUS SOMMES.wav"),
  "tu_es": require("../../assets/Les lecons douala/Le verbe etre/TU ES.wav"),
  "vous__tes": require("../../assets/Les lecons douala/Le verbe etre/VOUS ÊTES.wav"),
  "je_suis": require("../../assets/Les lecons douala/Le verbe etre/je suis.wav"),
  "cinq": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/cinq.wav"),
  "deux": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/deux.wav"),
  "huit": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/huit.wav"),
  "neuf": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/neuf.wav"),
  "quatre": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/quatre.wav"),
  "sept": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/sept.wav"),
  "six": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/six.wav"),
  "trois": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/trois.wav"),
  "un": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/un.wav"),
  "z_ro": require("../../assets/Les lecons douala/Les chiffres 1-9 en duala/zéro.wav"),
  "blanc": require("../../assets/Les lecons douala/Les couleur/blanc.wav"),
  "bleu_": require("../../assets/Les lecons douala/Les couleur/bleu .wav"),
  "jaune": require("../../assets/Les lecons douala/Les couleur/jaune.wav"),
  "noir": require("../../assets/Les lecons douala/Les couleur/noir.wav"),
  "rouge_": require("../../assets/Les lecons douala/Les couleur/rouge .wav"),
  "vert": require("../../assets/Les lecons douala/Les couleur/vert.wav"),
  "eux": require("../../assets/Les lecons douala/Les pronoms personnel/Eux.wav"),
  "lui": require("../../assets/Les lecons douala/Les pronoms personnel/Lui.wav"),
  "moi": require("../../assets/Les lecons douala/Les pronoms personnel/Moi.wav"),
  "nous": require("../../assets/Les lecons douala/Les pronoms personnel/Nous.wav"),
  "toi": require("../../assets/Les lecons douala/Les pronoms personnel/Toi.wav"),
  "vous": require("../../assets/Les lecons douala/Les pronoms personnel/Vous.wav"),
  "dimanche": require("../../assets/Les lecons douala/Les sept jour de la semaine/Dimanche.wav"),
  "jeudi": require("../../assets/Les lecons douala/Les sept jour de la semaine/Jeudi.wav"),
  "lundi": require("../../assets/Les lecons douala/Les sept jour de la semaine/Lundi.wav"),
  "mardi_": require("../../assets/Les lecons douala/Les sept jour de la semaine/Mardi .wav"),
  "mercredi": require("../../assets/Les lecons douala/Les sept jour de la semaine/Mercredi.wav"),
  "samedi": require("../../assets/Les lecons douala/Les sept jour de la semaine/Samedi.wav"),
  "vendredi": require("../../assets/Les lecons douala/Les sept jour de la semaine/Vendredi.wav"),
  "le_chiffre_0_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 0 en ngohmala.wav"),
  "le_chiffre_1_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 1 en ngohmala.wav"),
  "le_chiffre_3_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 3 en ngohmala.wav"),
  "le_chiffre_4_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 4 en ngohmala.wav"),
  "le_chiffre_6_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 6 en ngohmala.wav"),
  "le_chiffre_7_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 7 en ngohmala.wav"),
  "le_chiffre_8_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 8 en ngohmala.wav"),
  "le_chiffre_9_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 9 en ngohmala.wav"),
  "le_chiffre_2_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/le chiffre 2 en ngohmala.wav"),
  "le_chiffre_5_en_ngohmala": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/le chiffre 5 en ngohmala.wav"),
  "ga___j___j_achete_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/Gaə̂ jó (j'achete).wav"),
  "py___j___nous_achetons_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/pyə̂ jó  nous achetons).wav"),
  "p__j___vous_achetez_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/pô jó (vous achetez).wav"),
  "w_p_j___ils_ou_elles_achetent_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/wâp jó (ils ou elles achetent).wav"),
  "__j____tu_achete_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/ô jó ( tu achete).wav"),
  "__j___il_ou_elle_achete_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/ě jó (il ou elle achete).wav"),
  "ga___mpfa____je_mange_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/Gaə̂ mpfaə ( je mange).wav"),
  "py___mpfa___nous_mangeons_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/pyə̂ mpfaə (nous mangeons).wav"),
  "p__mpfa____vous_mangez_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/pô mpfaə ( vous mangez).wav"),
  "w_p_mpfa___ils_ou_elles_magent_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/wâp mpfaə (ils ou elles magent).wav"),
  "__mpfa___tu_mange_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/ô mpfaə (tu mange).wav"),
  "__mpfa____il_ou_elle_mange_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/ě mpfaə ( il ou elle mange).wav"),
  "ga___g____j_ai_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/Gaə̂ gə ( j'ai).wav"),
  "py___g____nous_avons_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/pyə̂ gə  (Nous avons).wav"),
  "p__g____vous_avez_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/pô gə ( vous avez).wav"),
  "w_p_g_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/wâp gə.wav"),
  "__g____tu_as_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/ô gə ( tu as).wav"),
  "__g___il_ou_elle_as_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/ě gə (il ou elle as).wav"),
  "ga___b_____je_suis_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/Gaə̂ bə́ ( je suis).wav"),
  "py___b____nus_sommes_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/pyə̂ bə́ (nus sommes).wav"),
  "p__b____vous_etes_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/pô bə́ (vous etes).wav"),
  "w_p_b____ils_ou_elles_sont_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/wâp bə́ (ils ou elles sont).wav"),
  "__b____tu_es_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/ô bə́ (tu es).wav"),
  "__b____il_ou_elle_est_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/ě bə́ (il ou elle est).wav"),
  "ga___gi___je_marche_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/Gaə̂ giŋ (Je marche).wav"),
  "py___gi____nous_marchons_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/pyə̂ giŋ ( nous marchons).wav"),
  "p__gi___vous_marchez_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/pô giŋ (vous marchez).wav"),
  "w_p_gi___ils_ou_elles_marchent_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/wâp giŋ (ils ou elles marchent).wav"),
  "__gi___tu_marche_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/ô giŋ (tu marche).wav"),
  "__gi___il_ou_elle_marche_": require("../../assets/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/ě giŋ (il ou elle marche).wav"),
  "bonjour_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonjour en duala.wav"),
  "bonne_chance_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonne chance en duala.wav"),
  "bonsoir_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonsoir en duala.wav"),
  "la_tente_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/La tente en duala.wav"),
  "le_bebe_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Le bebe en duala.wav"),
  "ma_famille_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Ma famille en duala.wav"),
  "mon_fr_re_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Mon Frère en duala.wav"),
  "l_oncle_en_douala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/l'oncle en douala.wav"),
  "les_amis_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les amis en duala.wav"),
  "les_enfants_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les enfants en duala.wav"),
  "les_grands_parents_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les grands parents en duala.wav"),
  "merci_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/merci en duala.wav"),
  "theme_0_exer_n2_rpsnse_3": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 Exer N2 Rpsnse 3.wav"),
  "theme_0_exer_2__les_grands_parents_en_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer 2 (les grands parents en duala).wav"),
  "theme_0_exer_2_rpsne_n1__les_amis_en_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer 2 Rpsne N1 (les amis en duala).wav"),
  "theme_0_exer_n2_rpsne_4": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer N2 Rpsne 4.wav"),
  "theme_0_exer_n3_rpsne_1": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 1.wav"),
  "theme_0_exer_n3_rpsne_2": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 2.wav"),
  "theme_0_exer_n3_rpsne_3": require("../../assets/Tout les themes audios de la langue duala/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 3.wav"),
  "theme_1_exer_n2_rpsne_1_la_girafe_en_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 1(La girafe en duala).wav"),
  "theme_1_exer_n2_rpsne_2": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 2.wav"),
  "theme_1_exer_n2_rpsne_3": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 3.wav"),
  "theme_1_exer_n2_rpsne_4": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 4.wav"),
  "theme_1_exer_n2_rpsne_5": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 5.wav"),
  "theme_1_exer_3_rpsne_4": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer 3 Rpsne 4.wav"),
  "theme_1_exer_n3_rpsne_1_les_abeilles_": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 1(les abeilles).wav"),
  "theme_1_exer_n3_rpsne_2__la_sauterelle_": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 2 (la sauterelle).wav"),
  "theme_1_exer_n3_rpsne_4___les_singes_": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 4 ( les singes).wav"),
  "l_huile_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/L'huile en duala.wav"),
  "la_girafe_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/La girafe en duala.wav"),
  "le_boef_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le boef en duala.wav"),
  "le_chat_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le chat en duala.wav"),
  "le_cheval_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le cheval en duala.wav"),
  "le_poison_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le poison en duala.wav"),
  "le_poulet_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le poulet en duala.wav"),
  "le_lion_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/le lion en duala.wav"),
  "le_termittes_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/le termittes en duala.wav"),
  "les_poulets_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/les poulets en duala.wav"),
  "l_eau_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/L'eau en duala.wav"),
  "la_farine_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La farine en duala.wav"),
  "la_flamme_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La flamme en duala.wav"),
  "la_tente_maternel_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La tente maternel en duala.wav"),
  "le_feu_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le feu en duala.wav"),
  "le_poison_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le poison en duala.wav"),
  "le_sel_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le sel en duala.wav"),
  "le_sucre_en_daula": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le sucre en daula.wav"),
  "le_couteau_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/le couteau en duala.wav"),
  "pierre_a_ecraser_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/pierre a ecraser en duala.wav"),
  "l_eau_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/L'eau en duala.wav"),
  "la_farine_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/La farine en duala.wav"),
  "le_poison_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/Le poison en duala.wav"),
  "le_gibier_en_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/le gibier en duala.wav"),
  "theme_2_exer_n3_rpsne_1": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 1.wav"),
  "theme_2_exer_n3_rpsne_2": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 2.wav"),
  "theme_2_exer_n3_rpsne_3": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 3.wav"),
  "theme_2_exer_n3_rpsne_4": require("../../assets/Tout les themes audios de la langue duala/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 4.wav"),
  "ce_menteau_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ce menteau en langue duala.wav"),
  "ce_pantalon_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ce pantalon en langue duala.wav"),
  "ces_boubou_en_lanue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ces boubou en lanue duala.wav"),
  "cette_chemise_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette chemise en langue duala.wav"),
  "cette_cullote_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette cullote en langue duala.wav"),
  "cette_habit_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette habit en langue duala.wav"),
  "ce_chapeau_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ce chapeau en langue duala.wav"),
  "ces_calecon_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ces calecon en langue duala.wav"),
  "ces_costumes_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ces costumes en langue duala.wav"),
  "cette_chaussure_en_langue_duala": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/cette chaussure en langue duala.wav"),
  "exer_n2_rpsne_2__ce_chapeau_en_langue_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/Exer N2 Rpsne 2 (ce chapeau en langue duala).wav"),
  "exer_n2_rpsne_3__ce_menteau_en_langue_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/Exer N2 Rpsne 3 (Ce menteau en langue duala).wav"),
  "exer_2_rpsne_n4": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer 2 Rpsne N4.wav"),
  "exer_2_rpsne_n5__le_travail_en_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer 2 Rpsne N5 (Le travail en duala).wav"),
  "exer_n2_rpsne_n1": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer N2 Rpsne N1.wav"),
  "exer_3_rpsne_n1__la_veste_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N1 (La veste duala).wav"),
  "exer_3_rpsne_n2__les_pentalons_en_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N2 (Les pentalons en duala).wav"),
  "exer_3_rpsne_n3": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N3.wav"),
  "exer_3_rpsne_n4": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N4.wav"),
  "exer_3_rpsne_n5__la_paire_de_babouche_en_duala_": require("../../assets/Tout les themes audios de la langue duala/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N5 (la paire de babouche en duala).wav"),
  "le_b_b_": require("../../assets/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/Le bébé.wav"),
  "l_oncle_": require("../../assets/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/L’oncle .wav"),
  "un_homme": require("../../assets/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/Un homme.wav"),
  "une_femme": require("../../assets/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/Une femme.wav"),
  "generik_makoune_short": require("../../assets/appthemesong/GENERIK MAKOUNE short.mp3"),
  "il_elle__on_a": require("../../assets/audio/Le verbe avoir/il elle  on a.wav"),
  "ils_elles_ont": require("../../assets/audio/Le verbe avoir/ils elles ont.wav"),
  "j_ai": require("../../assets/audio/Le verbe avoir/j ai.wav"),
  "nous_avons": require("../../assets/audio/Le verbe avoir/nous avons.wav"),
  "tu_as": require("../../assets/audio/Le verbe avoir/tu as.wav"),
  "vous_avez": require("../../assets/audio/Le verbe avoir/vous avez.wav"),
  "il_elle_est": require("../../assets/audio/Le verbe etre/IL ELLE EST.wav"),
  "ils_elles_sont": require("../../assets/audio/Le verbe etre/ILS ELLES SONT.wav"),
  "nous_sommes": require("../../assets/audio/Le verbe etre/NOUS SOMMES.wav"),
  "tu_es": require("../../assets/audio/Le verbe etre/TU ES.wav"),
  "vous__tes": require("../../assets/audio/Le verbe etre/VOUS ÊTES.wav"),
  "je_suis": require("../../assets/audio/Le verbe etre/je suis.wav"),
  "cinq": require("../../assets/audio/Les chiffres 1-9 en duala/cinq.wav"),
  "deux": require("../../assets/audio/Les chiffres 1-9 en duala/deux.wav"),
  "huit": require("../../assets/audio/Les chiffres 1-9 en duala/huit.wav"),
  "neuf": require("../../assets/audio/Les chiffres 1-9 en duala/neuf.wav"),
  "quatre": require("../../assets/audio/Les chiffres 1-9 en duala/quatre.wav"),
  "sept": require("../../assets/audio/Les chiffres 1-9 en duala/sept.wav"),
  "six": require("../../assets/audio/Les chiffres 1-9 en duala/six.wav"),
  "trois": require("../../assets/audio/Les chiffres 1-9 en duala/trois.wav"),
  "un": require("../../assets/audio/Les chiffres 1-9 en duala/un.wav"),
  "z_ro": require("../../assets/audio/Les chiffres 1-9 en duala/zéro.wav"),
  "blanc": require("../../assets/audio/Les couleur/blanc.wav"),
  "bleu_": require("../../assets/audio/Les couleur/bleu .wav"),
  "jaune": require("../../assets/audio/Les couleur/jaune.wav"),
  "noir": require("../../assets/audio/Les couleur/noir.wav"),
  "rouge_": require("../../assets/audio/Les couleur/rouge .wav"),
  "vert": require("../../assets/audio/Les couleur/vert.wav"),
  "eux": require("../../assets/audio/Les pronoms personnel/Eux.wav"),
  "lui": require("../../assets/audio/Les pronoms personnel/Lui.wav"),
  "moi": require("../../assets/audio/Les pronoms personnel/Moi.wav"),
  "nous": require("../../assets/audio/Les pronoms personnel/Nous.wav"),
  "toi": require("../../assets/audio/Les pronoms personnel/Toi.wav"),
  "vous": require("../../assets/audio/Les pronoms personnel/Vous.wav"),
  "dimanche": require("../../assets/audio/Les sept jour de la semaine/Dimanche.wav"),
  "jeudi": require("../../assets/audio/Les sept jour de la semaine/Jeudi.wav"),
  "lundi": require("../../assets/audio/Les sept jour de la semaine/Lundi.wav"),
  "mardi_": require("../../assets/audio/Les sept jour de la semaine/Mardi .wav"),
  "mercredi": require("../../assets/audio/Les sept jour de la semaine/Mercredi.wav"),
  "samedi": require("../../assets/audio/Les sept jour de la semaine/Samedi.wav"),
  "vendredi": require("../../assets/audio/Les sept jour de la semaine/Vendredi.wav"),
  "bonjour_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonjour en duala.wav"),
  "bonne_chance_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonne chance en duala.wav"),
  "bonsoir_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonsoir en duala.wav"),
  "la_tente_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/La tente en duala.wav"),
  "le_bebe_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Le bebe en duala.wav"),
  "ma_famille_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Ma famille en duala.wav"),
  "mon_fr_re_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Mon Frère en duala.wav"),
  "l_oncle_en_douala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/l'oncle en douala.wav"),
  "les_amis_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les amis en duala.wav"),
  "les_enfants_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les enfants en duala.wav"),
  "les_grands_parents_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les grands parents en duala.wav"),
  "merci_en_duala": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/merci en duala.wav"),
  "theme_0_exer_n2_rpsnse_3": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 Exer N2 Rpsnse 3.wav"),
  "theme_0_exer_2__les_grands_parents_en_duala_": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer 2 (les grands parents en duala).wav"),
  "theme_0_exer_2_rpsne_n1__les_amis_en_duala_": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer 2 Rpsne N1 (les amis en duala).wav"),
  "theme_0_exer_n2_rpsne_4": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer N2 Rpsne 4.wav"),
  "theme_0_exer_n3_rpsne_1": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 1.wav"),
  "theme_0_exer_n3_rpsne_2": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 2.wav"),
  "theme_0_exer_n3_rpsne_3": require("../../assets/audio/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 3.wav"),
  "theme_1_exer_n2_rpsne_1_la_girafe_en_duala_": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 1(La girafe en duala).wav"),
  "theme_1_exer_n2_rpsne_2": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 2.wav"),
  "theme_1_exer_n2_rpsne_3": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 3.wav"),
  "theme_1_exer_n2_rpsne_4": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 4.wav"),
  "theme_1_exer_n2_rpsne_5": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 5.wav"),
  "theme_1_exer_3_rpsne_4": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer 3 Rpsne 4.wav"),
  "theme_1_exer_n3_rpsne_1_les_abeilles_": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 1(les abeilles).wav"),
  "theme_1_exer_n3_rpsne_2__la_sauterelle_": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 2 (la sauterelle).wav"),
  "theme_1_exer_n3_rpsne_4___les_singes_": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 4 ( les singes).wav"),
  "l_huile_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/L'huile en duala.wav"),
  "la_girafe_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/La girafe en duala.wav"),
  "le_boef_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le boef en duala.wav"),
  "le_chat_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le chat en duala.wav"),
  "le_cheval_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le cheval en duala.wav"),
  "le_poison_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le poison en duala.wav"),
  "le_poulet_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le poulet en duala.wav"),
  "le_lion_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/le lion en duala.wav"),
  "le_termittes_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/le termittes en duala.wav"),
  "les_poulets_en_duala": require("../../assets/audio/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/les poulets en duala.wav"),
  "l_eau_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/L'eau en duala.wav"),
  "la_farine_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La farine en duala.wav"),
  "la_flamme_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La flamme en duala.wav"),
  "la_tente_maternel_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La tente maternel en duala.wav"),
  "le_feu_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le feu en duala.wav"),
  "le_poison_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le poison en duala.wav"),
  "le_sel_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le sel en duala.wav"),
  "le_sucre_en_daula": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le sucre en daula.wav"),
  "le_couteau_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/le couteau en duala.wav"),
  "pierre_a_ecraser_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/pierre a ecraser en duala.wav"),
  "l_eau_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/L'eau en duala.wav"),
  "la_farine_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/La farine en duala.wav"),
  "le_poison_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/Le poison en duala.wav"),
  "le_gibier_en_duala": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/le gibier en duala.wav"),
  "theme_2_exer_n3_rpsne_1": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 1.wav"),
  "theme_2_exer_n3_rpsne_2": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 2.wav"),
  "theme_2_exer_n3_rpsne_3": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 3.wav"),
  "theme_2_exer_n3_rpsne_4": require("../../assets/audio/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 4.wav"),
  "ce_menteau_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ce menteau en langue duala.wav"),
  "ce_pantalon_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ce pantalon en langue duala.wav"),
  "ces_boubou_en_lanue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ces boubou en lanue duala.wav"),
  "cette_chemise_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette chemise en langue duala.wav"),
  "cette_cullote_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette cullote en langue duala.wav"),
  "cette_habit_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette habit en langue duala.wav"),
  "ce_chapeau_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ce chapeau en langue duala.wav"),
  "ces_calecon_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ces calecon en langue duala.wav"),
  "ces_costumes_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ces costumes en langue duala.wav"),
  "cette_chaussure_en_langue_duala": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/cette chaussure en langue duala.wav"),
  "exer_n2_rpsne_2__ce_chapeau_en_langue_duala_": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/Exer N2 Rpsne 2 (ce chapeau en langue duala).wav"),
  "exer_n2_rpsne_3__ce_menteau_en_langue_duala_": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/Exer N2 Rpsne 3 (Ce menteau en langue duala).wav"),
  "exer_2_rpsne_n4": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer 2 Rpsne N4.wav"),
  "exer_2_rpsne_n5__le_travail_en_duala_": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer 2 Rpsne N5 (Le travail en duala).wav"),
  "exer_n2_rpsne_n1": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer N2 Rpsne N1.wav"),
  "exer_3_rpsne_n1__la_veste_duala_": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N1 (La veste duala).wav"),
  "exer_3_rpsne_n2__les_pentalons_en_duala_": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N2 (Les pentalons en duala).wav"),
  "exer_3_rpsne_n3": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N3.wav"),
  "exer_3_rpsne_n4": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N4.wav"),
  "exer_3_rpsne_n5__la_paire_de_babouche_en_duala_": require("../../assets/audio/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N5 (la paire de babouche en duala).wav"),
};
