// AUTO-GENERATED MAP FOR LOCAL ASSETS
export const IMAGES_MAP = {
  "android_icon_background": require("../../assets/Avatar-images -profile-picker/android-icon-background.png"),
  "android_icon_foreground": require("../../assets/Avatar-images -profile-picker/android-icon-foreground.png"),
  "android_icon_monochrome": require("../../assets/Avatar-images -profile-picker/android-icon-monochrome.png"),
  "avatar_cuisine": require("../../assets/Avatar-images -profile-picker/avatar-cuisine.webp"),
  "avatar_famille": require("../../assets/Avatar-images -profile-picker/avatar-famille.png"),
  "avatar_felix": require("../../assets/Avatar-images -profile-picker/avatar-felix.png"),
  "avatar_kandem": require("../../assets/Avatar-images -profile-picker/avatar-kandem.avif"),
  "avatar_kandem": require("../../assets/Avatar-images -profile-picker/avatar-kandem.png"),
  "avatar_ngon": require("../../assets/Avatar-images -profile-picker/avatar-ngon.avif"),
  "avatar_ngon": require("../../assets/Avatar-images -profile-picker/avatar-ngon.png"),
  "avatar_paul": require("../../assets/Avatar-images -profile-picker/avatar-paul.png"),
  "avatar_sophie": require("../../assets/Avatar-images -profile-picker/avatar-sophie.avif"),
  "avatar_sophie": require("../../assets/Avatar-images -profile-picker/avatar-sophie.png"),
  "avatar_tjega": require("../../assets/Avatar-images -profile-picker/avatar-tjega.avif"),
  "avatar_tjega": require("../../assets/Avatar-images -profile-picker/avatar-tjega.png"),
  "avatar_user": require("../../assets/Avatar-images -profile-picker/avatar-user.png"),
  "avatar_vetement": require("../../assets/Avatar-images -profile-picker/avatar-vetement.png"),
  "boat": require("../../assets/Avatar-images -profile-picker/boat.png"),
  "camel": require("../../assets/Avatar-images -profile-picker/camel.png"),
  "colla": require("../../assets/Avatar-images -profile-picker/colla.png"),
  "favicon": require("../../assets/Avatar-images -profile-picker/favicon.png"),
  "forgot": require("../../assets/Avatar-images -profile-picker/forgot.webp"),
  "icon": require("../../assets/Avatar-images -profile-picker/icon.png"),
  "island": require("../../assets/Avatar-images -profile-picker/island.png"),
  "jungle_background": require("../../assets/Avatar-images -profile-picker/jungle_background.jpg"),
  "lock": require("../../assets/Avatar-images -profile-picker/lock.png"),
  "logo": require("../../assets/Avatar-images -profile-picker/logo.png"),
  "mountain_large": require("../../assets/Avatar-images -profile-picker/mountain-large.png"),
  "mountain_small": require("../../assets/Avatar-images -profile-picker/mountain-small.png"),
  "otp": require("../../assets/Avatar-images -profile-picker/otp.png"),
  "partial_react_logo": require("../../assets/Avatar-images -profile-picker/partial-react-logo.png"),
  "pyramid_large": require("../../assets/Avatar-images -profile-picker/pyramid-large.png"),
  "pyramid_small": require("../../assets/Avatar-images -profile-picker/pyramid-small.png"),
  "react_logo": require("../../assets/Avatar-images -profile-picker/react-logo.png"),
  "react_logo_2x": require("../../assets/Avatar-images -profile-picker/react-logo@2x.png"),
  "react_logo_3x": require("../../assets/Avatar-images -profile-picker/react-logo@3x.png"),
  "reset": require("../../assets/Avatar-images -profile-picker/reset.webp"),
  "sign_in": require("../../assets/Avatar-images -profile-picker/sign-in.png"),
  "sign_up": require("../../assets/Avatar-images -profile-picker/sign-up.png"),
  "sphinx": require("../../assets/Avatar-images -profile-picker/sphinx.png"),
  "splash_icon": require("../../assets/Avatar-images -profile-picker/splash-icon.png"),
  "winding_path": require("../../assets/Avatar-images -profile-picker/winding_path.jpg"),
  "aunty": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/aunty.jpg"),
  "baby": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/baby.jpg"),
  "children": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/children.jpg"),
  "couple": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/couple.jpg"),
  "family": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/family.jpg"),
  "grandparents": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/grandparents.jpg"),
  "uncle": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 0 des exercises/uncle.jpg"),
  "bird": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/bird.jpg"),
  "cocroach": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/cocroach.webp"),
  "elephant": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/elephant.jpg"),
  "fish": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/fish.jpg"),
  "lion": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/lion.jpg"),
  "monkeys": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/monkeys.jpg"),
  "pigs": require("../../assets/Images du thème 3/Les images de muléma/Images du theme 1 de tout les exercises/pigs.jpg"),
  "burn_fire": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/burn-fire.jpg"),
  "fire": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/fire.jpg"),
  "flour": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/flour.jpg"),
  "fork": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/fork.jpg"),
  "multer_pistol": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/multer-pistol.jpg"),
  "olive_oil": require("../../assets/Images du thème 3/Les images de muléma/Images du thème 2/olive-oil.jpg"),
  "ladder_shoes": require("../../assets/Images du thème 3/ladder-shoes.webp"),
  "shoes": require("../../assets/Images du thème 3/shoes.webp"),
  "suit": require("../../assets/Images du thème 3/suit.webp"),
  "t_shirt": require("../../assets/Images du thème 3/t-shirt.jpg"),
  "tie": require("../../assets/Images du thème 3/tie.webp"),
  "trouser": require("../../assets/Images du thème 3/trouser.jpg"),
};

export const AUDIOS_MAP = {
  "generik_makoune_short": require("../../assets/appthemesong/GENERIK MAKOUNE short.mp3"),
  "il_elle__on_a": require("../../assets/audio/Le verbe avoir/il elle  on a.mp3"),
  "ils_elles_ont": require("../../assets/audio/Le verbe avoir/ils elles ont.mp3"),
  "j_ai": require("../../assets/audio/Le verbe avoir/j ai.mp3"),
  "nous_avons": require("../../assets/audio/Le verbe avoir/nous avons.mp3"),
  "tu_as": require("../../assets/audio/Le verbe avoir/tu as.mp3"),
  "vous_avez": require("../../assets/audio/Le verbe avoir/vous avez.mp3"),
  "il_elle_est": require("../../assets/audio/Le verbe etre/IL ELLE EST.mp3"),
  "ils_elles_sont": require("../../assets/audio/Le verbe etre/ILS ELLES SONT.mp3"),
  "nous_sommes": require("../../assets/audio/Le verbe etre/NOUS SOMMES.mp3"),
  "tu_es": require("../../assets/audio/Le verbe etre/TU ES.mp3"),
  "vous__tes": require("../../assets/audio/Le verbe etre/VOUS ÊTES.mp3"),
  "je_suis": require("../../assets/audio/Le verbe etre/je suis.mp3"),
  "blanc": require("../../assets/audio/Les couleur/blanc.mp3"),
  "bleu_": require("../../assets/audio/Les couleur/bleu .mp3"),
  "jaune": require("../../assets/audio/Les couleur/jaune.mp3"),
  "noir": require("../../assets/audio/Les couleur/noir.mp3"),
  "rouge_": require("../../assets/audio/Les couleur/rouge .mp3"),
  "vert": require("../../assets/audio/Les couleur/vert.mp3"),
  "eux": require("../../assets/audio/Les pronoms personnel/Eux.mp3"),
  "lui": require("../../assets/audio/Les pronoms personnel/Lui.mp3"),
  "moi": require("../../assets/audio/Les pronoms personnel/Moi.mp3"),
  "nous": require("../../assets/audio/Les pronoms personnel/Nous.mp3"),
  "toi": require("../../assets/audio/Les pronoms personnel/Toi.mp3"),
  "vous": require("../../assets/audio/Les pronoms personnel/Vous.mp3"),
  "dimanche": require("../../assets/audio/Les sept jour de la semaine/Dimanche.mp3"),
  "jeudi": require("../../assets/audio/Les sept jour de la semaine/Jeudi.mp3"),
  "lundi": require("../../assets/audio/Les sept jour de la semaine/Lundi.mp3"),
  "mardi_": require("../../assets/audio/Les sept jour de la semaine/Mardi .mp3"),
  "mercredi": require("../../assets/audio/Les sept jour de la semaine/Mercredi.mp3"),
  "samedi": require("../../assets/audio/Les sept jour de la semaine/Samedi.mp3"),
  "vendredi": require("../../assets/audio/Les sept jour de la semaine/Vendredi.mp3"),
  "dimanche": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/dimanche.mp3"),
  "jeudi": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/jeudi.mp3"),
  "lundi": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/lundi.mp3"),
  "mardi": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/mardi.mp3"),
  "mercredi": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/mercredi.mp3"),
  "samedi": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/samedi.mp3"),
  "vendredi": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les 7jours de la semaine en Bassa/vendredi.mp3"),
  "il_ou_elle_a": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/il ou elle a.mp3"),
  "ils_ou_elles_ont": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/ils ou elles ont.mp3"),
  "j_aiwav": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/j'aiwav.mp3"),
  "nous_avons": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/nous avons.mp3"),
  "tu_as": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/tu as.mp3"),
  "vous_avez": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Avoir en Langue Bassa/vous avez.mp3"),
  "il_ou_elle_mange": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/il ou elle mange.mp3"),
  "ils_ou_elle_mangent": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/ils ou elle mangent.mp3"),
  "je_mange": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/je mange.mp3"),
  "nous_mangeons": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/nous mangeons.mp3"),
  "tu_manges": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/tu manges.mp3"),
  "vous_mangez": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Manger en Langue Bassa/vous mangez.mp3"),
  "il_ou_elle_marche": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/il ou elle marche.mp3"),
  "ils_ou_elles_marchent": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/ils ou elles marchent.mp3"),
  "je_marche": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/je marche.mp3"),
  "nous_marchons": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/nous marchons.mp3"),
  "tu_marches": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/tu marches.mp3"),
  "vous_marchez": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe Marcher en langue Bassa/vous marchez.mp3"),
  "il_ou_elle_achete": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/il ou elle achete.mp3"),
  "ils_ou_elles_achetent": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/ils ou elles achetent.mp3"),
  "j_achete": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/j'achete.mp3"),
  "nous_achetons": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/nous achetons.mp3"),
  "tu_achetes": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/tu achetes.mp3"),
  "vous_achetez": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe acheter en Bassa/vous achetez.mp3"),
  "il_elle_on_est__1_": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/il elle on est (1).mp3"),
  "ils_elles_sont__1_": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/ils elles sont (1).mp3"),
  "je_suis__1_": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/je suis (1).mp3"),
  "nous_sommes__1_": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/nous sommes (1).mp3"),
  "tu_es__2_": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/tu es (2).mp3"),
  "vous_etes__1_": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe etre en bassa/vous etes (1).mp3"),
  "il_ou_elle_prend": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/il ou elle prend.mp3"),
  "ils_ou_elles_prennent": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/ils ou elles prennent.mp3"),
  "je_prends": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/je prends.mp3"),
  "nous_prenons": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/nous prenons.mp3"),
  "tu_prends": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/tu prends.mp3"),
  "vous_prenez": require("../../assets/bassa/lessons/Les lecons de la langue Bassa/Les verbes en bassa/Le verbe prendre en langue Bassa/vous prenez.mp3"),
  "le_b_b_": require("../../assets/bassa/themes/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/Le bébé.mp3"),
  "l_oncle_": require("../../assets/bassa/themes/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/L’oncle .mp3"),
  "un_homme": require("../../assets/bassa/themes/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/Un homme.mp3"),
  "une_femme": require("../../assets/bassa/themes/Tout les themes de la langue Bassa/Theme 0 de la langue Bassa( La famille)/Exercise 3 du theme 0 en Bassa/Une femme.mp3"),
  "cinq": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/cinq.mp3"),
  "deux": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/deux.mp3"),
  "huit": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/huit.mp3"),
  "neuf": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/neuf.mp3"),
  "quatre": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/quatre.mp3"),
  "sept": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/sept.mp3"),
  "six": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/six.mp3"),
  "trois": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/trois.mp3"),
  "un": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/un.mp3"),
  "z_ro": require("../../assets/duala/audio_voices/Les chiffres 1-9 en duala/zéro.mp3"),
  "bonjour_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonjour en duala.mp3"),
  "bonne_chance_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonne chance en duala.mp3"),
  "bonsoir_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Bonsoir en duala.mp3"),
  "la_tente_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/La tente en duala.mp3"),
  "le_bebe_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Le bebe en duala.mp3"),
  "ma_famille_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Ma famille en duala.mp3"),
  "mon_fr_re_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/Mon Frère en duala.mp3"),
  "l_oncle_en_douala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/l'oncle en douala.mp3"),
  "les_amis_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les amis en duala.mp3"),
  "les_enfants_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les enfants en duala.mp3"),
  "les_grands_parents_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/les grands parents en duala.mp3"),
  "merci_en_duala": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 1 du theme 0 en duala/merci en duala.mp3"),
  "theme_0_exer_n2_rpsnse_3": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 Exer N2 Rpsnse 3.mp3"),
  "theme_0_exer_2__les_grands_parents_en_duala_": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer 2 (les grands parents en duala).mp3"),
  "theme_0_exer_2_rpsne_n1__les_amis_en_duala_": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer 2 Rpsne N1 (les amis en duala).mp3"),
  "theme_0_exer_n2_rpsne_4": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 2 du theme 0 en duala/Theme 0 exer N2 Rpsne 4.mp3"),
  "theme_0_exer_n3_rpsne_1": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 1.mp3"),
  "theme_0_exer_n3_rpsne_2": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 2.mp3"),
  "theme_0_exer_n3_rpsne_3": require("../../assets/duala/audio_voices/Theme 0 de la langue duala (Voices)/Exercise 3 du theme 0 en duala/Theme 0 exer N3 Rpsne 3.mp3"),
  "theme_1_exer_n2_rpsne_1_la_girafe_en_duala_": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 1(La girafe en duala).mp3"),
  "theme_1_exer_n2_rpsne_2": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 2.mp3"),
  "theme_1_exer_n2_rpsne_3": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 3.mp3"),
  "theme_1_exer_n2_rpsne_4": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 4.mp3"),
  "theme_1_exer_n2_rpsne_5": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 2 du theme 1 en duala/Theme 1 exer N2 Rpsne 5.mp3"),
  "theme_1_exer_3_rpsne_4": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer 3 Rpsne 4.mp3"),
  "theme_1_exer_n3_rpsne_1_les_abeilles_": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 1(les abeilles).mp3"),
  "theme_1_exer_n3_rpsne_2__la_sauterelle_": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 2 (la sauterelle).mp3"),
  "theme_1_exer_n3_rpsne_4___les_singes_": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/Exercise 3 du theme 1 en duala/Theme 1 exer N3 Rpsne 4 ( les singes).mp3"),
  "l_huile_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/L'huile en duala.mp3"),
  "la_girafe_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/La girafe en duala.mp3"),
  "le_boef_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le boef en duala.mp3"),
  "le_chat_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le chat en duala.mp3"),
  "le_cheval_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le cheval en duala.mp3"),
  "le_poison_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le poison en duala.mp3"),
  "le_poulet_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/Le poulet en duala.mp3"),
  "le_lion_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/le lion en duala.mp3"),
  "le_termittes_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/le termittes en duala.mp3"),
  "les_poulets_en_duala": require("../../assets/duala/audio_voices/Theme 1 en duala (voices)/les exercises/exercise 1 du Theme 1 en duala/les poulets en duala.mp3"),
  "l_eau_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/L'eau en duala.mp3"),
  "la_farine_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La farine en duala.mp3"),
  "la_flamme_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La flamme en duala.mp3"),
  "la_tente_maternel_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/La tente maternel en duala.mp3"),
  "le_feu_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le feu en duala.mp3"),
  "le_poison_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le poison en duala.mp3"),
  "le_sel_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le sel en duala.mp3"),
  "le_sucre_en_daula": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/Le sucre en daula.mp3"),
  "le_couteau_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/le couteau en duala.mp3"),
  "pierre_a_ecraser_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 1 du theme 2/pierre a ecraser en duala.mp3"),
  "l_eau_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/L'eau en duala.mp3"),
  "la_farine_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/La farine en duala.mp3"),
  "le_poison_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/Le poison en duala.mp3"),
  "le_gibier_en_duala": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 2 du theme 2/le gibier en duala.mp3"),
  "theme_2_exer_n3_rpsne_1": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 1.mp3"),
  "theme_2_exer_n3_rpsne_2": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 2.mp3"),
  "theme_2_exer_n3_rpsne_3": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 3.mp3"),
  "theme_2_exer_n3_rpsne_4": require("../../assets/duala/audio_voices/Theme 2 de la langue duala (voices)/Exercise 3 du theme 2/Theme 2 exer N3 Rpsne 4.mp3"),
  "ce_menteau_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ce menteau en langue duala.mp3"),
  "ce_pantalon_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ce pantalon en langue duala.mp3"),
  "ces_boubou_en_lanue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Ces boubou en lanue duala.mp3"),
  "cette_chemise_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette chemise en langue duala.mp3"),
  "cette_cullote_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette cullote en langue duala.mp3"),
  "cette_habit_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/Cette habit en langue duala.mp3"),
  "ce_chapeau_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ce chapeau en langue duala.mp3"),
  "ces_calecon_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ces calecon en langue duala.mp3"),
  "ces_costumes_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/ces costumes en langue duala.mp3"),
  "cette_chaussure_en_langue_duala": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 1 du theme 5/cette chaussure en langue duala.mp3"),
  "exer_n2_rpsne_2__ce_chapeau_en_langue_duala_": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/Exer N2 Rpsne 2 (ce chapeau en langue duala).mp3"),
  "exer_n2_rpsne_3__ce_menteau_en_langue_duala_": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/Exer N2 Rpsne 3 (Ce menteau en langue duala).mp3"),
  "exer_2_rpsne_n4": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer 2 Rpsne N4.mp3"),
  "exer_2_rpsne_n5__le_travail_en_duala_": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer 2 Rpsne N5 (Le travail en duala).mp3"),
  "exer_n2_rpsne_n1": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 2 du theme 5 en duala/exer N2 Rpsne N1.mp3"),
  "exer_3_rpsne_n1__la_veste_duala_": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N1 (La veste duala).mp3"),
  "exer_3_rpsne_n2__les_pentalons_en_duala_": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N2 (Les pentalons en duala).mp3"),
  "exer_3_rpsne_n3": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N3.mp3"),
  "exer_3_rpsne_n4": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N4.mp3"),
  "exer_3_rpsne_n5__la_paire_de_babouche_en_duala_": require("../../assets/duala/audio_voices/Theme 3 de la langue duala (voices)/Exercise 3 du theme 5 en duala/exer 3 Rpsne N5 (la paire de babouche en duala).mp3"),
  "mama_en_langue_nghomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/Mama en langue nghomala.mp3"),
  "la_tante_maternelleen_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/la tante maternelleen ngohmala.mp3"),
  "la_tante_paternelle_en_nghomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/la tante paternelle en nghomala.mp3"),
  "le_bebe_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/le bebe en ngohmala.mp3"),
  "les_amis_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/les amis en ngohmala.mp3"),
  "les_enfants_en_nghomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/les enfants en nghomala.mp3"),
  "les_grand_parents_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/les grand parents en ngohmala.mp3"),
  "loncle_maternel_en_nghomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/loncle maternel en nghomala.mp3"),
  "loncle_paternel_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/loncle paternel en ngomala.mp3"),
  "papa_en_langue_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 1 ngomala/papa en langue ngomala.mp3"),
  "exer_n2_rpsne_1_papa_": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/Exer N2 Rpsne 1(papa).mp3"),
  "exer_n2_rpsne_2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/exer N2 Rpsne 2.mp3"),
  "exer_n2_rpsne_3__les_enfants_": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/exer N2 Rpsne 3 (les enfants).mp3"),
  "exer_n2_rpsne_4": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 2 ngomala/exer N2 Rpsne 4.mp3"),
  "exer_n3_rpsne_5": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/Exer N3 Rpsne 5.mp3"),
  "exer_n6_rpsne_2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer N6 Rpsne 2.mp3"),
  "exer_n6_rpsne_3": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer N6 Rpsne 3.mp3"),
  "exer_n6_rpsne_4": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer N6 Rpsne 4.mp3"),
  "exer_n6_rpsne_1": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 0 ghomala/exercise 3 ngomala/exer n6 Rpsne 1.mp3"),
  "l_huile_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/L'huile en ngomala.mp3"),
  "le_poulet_en_ngomala__ca_ne_change_pasau_pluriel_": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/Le poulet en ngomala (ca ne change pasau pluriel).mp3"),
  "le_boeuf_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/le boeuf en ngomala.mp3"),
  "le_lion_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/le lion en ngomala.mp3"),
  "le_poisson_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/le poisson en ngohmala.mp3"),
  "les_termites_en_langue_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 1 theme 1 ngomala/les Termites en langue ngomala.mp3"),
  "exer_2_rpsne_1": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 1.mp3"),
  "exer_2_rpsne_2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 2.mp3"),
  "exer_2_rpsne_3_les_sangliers": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 3 les sangliers.mp3"),
  "exer_2_rpsne_4": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne 4.mp3"),
  "exer_2_rpsne_n5_l_elephant": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 2  du Theme 1 en ngomala/exer 2 Rpsne N5 l elephant.mp3"),
  "exer_3_rpsne_1_l_abeille": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 Rpsne 1 l abeille.mp3"),
  "exer_3_rpsne_3": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 Rpsne 3.mp3"),
  "exer_3_rpsne_n4_les_singes": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 Rpsne N4 les singes.mp3"),
  "exer_3_rpsne_2_la_sauterelle": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 1 ghomala/Exercise 3 du theme 1 en ngohmala/exer 3 rpsne 2 la sauterelle.mp3"),
  "l_huile_en_ngohmala_theme_2_exer_1": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/L huile en ngohmala theme 2 exer 1.mp3"),
  "la_farine_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/La farine en ngohmala.mp3"),
  "la_flamme_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/La flamme en ngohmala.mp3"),
  "la_piere_a_ecrasser_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/La piere a ecrasser en ngohmala.mp3"),
  "le_sucre_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le Sucre en ngohmala.mp3"),
  "le_couteau_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le couteau en ngohmala.mp3"),
  "le_mortier_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le mortier en ngohmala.mp3"),
  "le_sel_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/Le sel en ngohmala.mp3"),
  "l_eau_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/l'eau en ngohmala.mp3"),
  "le_feu_en_ngohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 1 du theme 2 en ngohmala/le feu en ngohmala.mp3"),
  "exer_2_rpsne_1": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 1.mp3"),
  "exer_2_rpsne_2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 2.mp3"),
  "exer_2_rpsne_3": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 3.mp3"),
  "exer_2_rpsne_4": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 4.mp3"),
  "exer_2_rpsne_5": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 2 du theme 2 en ngohmala/exer 2 Rpsne 5.mp3"),
  "exer_2_rpsne_n2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 2 Rpsne N2.mp3"),
  "exer_3_rpsne_n1": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 Rpsne N1.mp3"),
  "exer_3_rpsne_n4": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 Rpsne N4.mp3"),
  "exer_3_rpsne_n5": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 Rpsne N5.mp3"),
  "exer_3_rpsne_n3": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 2 ghomala/Exercise 3 du theme 2 en ngohmala/exer 3 rpsne N3.mp3"),
  "ce_chapau": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ce chapau.mp3"),
  "ce_mentau": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ce mentau.mp3"),
  "ces_boubous": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ces boubous.mp3"),
  "ces_calecon_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ces calecon en ngomala.mp3"),
  "ces_costumes_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Ces costumes en ngomala.mp3"),
  "cette_chaussure_en_ngomala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette chaussure en ngomala.mp3"),
  "cette_chemise_en_gohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette chemise en gohmala.mp3"),
  "cette_cullote": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette cullote.mp3"),
  "cette_habit_en_gohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/Cette habit en gohmala.mp3"),
  "ce_pentalon": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/ce pentalon.mp3"),
  "cette_chemise_gohmala": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 1 du theme 3 en ngohmala/cette chemise gohmala.mp3"),
  "exer_2_rpsne_1_la_cravate": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 2 Rpsne 1 la cravate.mp3"),
  "exer_2_rpsne_2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 2 Rpsne 2.mp3"),
  "exer_2_rpsne_3": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 2 Rpsne 3.mp3"),
  "exer_3_rpsne_4": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 2 du theme 3 en ghomala/exer 3 Rpsne 4.mp3"),
  "exer_3_rpsne_4__les_pairs_de_babouche_": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne 4 (les pairs de babouche).mp3"),
  "exer_3_rpsne_n1_la_vesste": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne N1 la vesste.mp3"),
  "exer_3_rpsne_n2": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne N2.mp3"),
  "exer_3_rpsne_n3": require("../../assets/ghomala/audio_voices/Audio de tout les theme en ngohmala/Theme 3 en ghomala/exercise 3 du theme 3 en ghomala/exer 3 Rpsne N3.mp3"),
  "le_chiffre_0_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 0 en ngohmala.mp3"),
  "le_chiffre_1_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 1 en ngohmala.mp3"),
  "le_chiffre_3_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 3 en ngohmala.mp3"),
  "le_chiffre_4_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 4 en ngohmala.mp3"),
  "le_chiffre_6_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 6 en ngohmala.mp3"),
  "le_chiffre_7_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 7 en ngohmala.mp3"),
  "le_chiffre_8_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 8 en ngohmala.mp3"),
  "le_chiffre_9_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/Le chiffre 9 en ngohmala.mp3"),
  "le_chiffre_2_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/le chiffre 2 en ngohmala.mp3"),
  "le_chiffre_5_en_ngohmala": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les chiffres 0-9 en gohmala et les jours de la semaine en ghomala/le chiffre 5 en ngohmala.mp3"),
  "ga___j___j_achete_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/Gaə̂ jó (j'achete).mp3"),
  "py___j___nous_achetons_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/pyə̂ jó  nous achetons).mp3"),
  "p__j___vous_achetez_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/pô jó (vous achetez).mp3"),
  "w_p_j___ils_ou_elles_achetent_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/wâp jó (ils ou elles achetent).mp3"),
  "__j____tu_achete_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/ô jó ( tu achete).mp3"),
  "__j___il_ou_elle_achete_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe  acheter en ghomala/ě jó (il ou elle achete).mp3"),
  "ga___mpfa____je_mange_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/Gaə̂ mpfaə ( je mange).mp3"),
  "py___mpfa___nous_mangeons_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/pyə̂ mpfaə (nous mangeons).mp3"),
  "p__mpfa____vous_mangez_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/pô mpfaə ( vous mangez).mp3"),
  "w_p_mpfa___ils_ou_elles_magent_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/wâp mpfaə (ils ou elles magent).mp3"),
  "__mpfa___tu_mange_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/ô mpfaə (tu mange).mp3"),
  "__mpfa____il_ou_elle_mange_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe Manger en ghomala/ě mpfaə ( il ou elle mange).mp3"),
  "ga___g____j_ai_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/Gaə̂ gə ( j'ai).mp3"),
  "py___g____nous_avons_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/pyə̂ gə  (Nous avons).mp3"),
  "p__g____vous_avez_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/pô gə ( vous avez).mp3"),
  "w_p_g_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/wâp gə.mp3"),
  "__g____tu_as_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/ô gə ( tu as).mp3"),
  "__g___il_ou_elle_as_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe avoir en ghomala/ě gə (il ou elle as).mp3"),
  "ga___b_____je_suis_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/Gaə̂ bə́ ( je suis).mp3"),
  "py___b____nus_sommes_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/pyə̂ bə́ (nus sommes).mp3"),
  "p__b____vous_etes_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/pô bə́ (vous etes).mp3"),
  "w_p_b____ils_ou_elles_sont_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/wâp bə́ (ils ou elles sont).mp3"),
  "__b____tu_es_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/ô bə́ (tu es).mp3"),
  "__b____il_ou_elle_est_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe etre en ghomala/ě bə́ (il ou elle est).mp3"),
  "ga___gi___je_marche_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/Gaə̂ giŋ (Je marche).mp3"),
  "py___gi____nous_marchons_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/pyə̂ giŋ ( nous marchons).mp3"),
  "p__gi___vous_marchez_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/pô giŋ (vous marchez).mp3"),
  "w_p_gi___ils_ou_elles_marchent_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/wâp giŋ (ils ou elles marchent).mp3"),
  "__gi___tu_marche_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/ô giŋ (tu marche).mp3"),
  "__gi___il_ou_elle_marche_": require("../../assets/ghomala/lessons/Less leçons du ghomala/Less leçons de la langeu ghomala/les verbes en gohmala/Le verbe marcher en ghomala/ě giŋ (il ou elle marche).mp3"),
};
